# docker-compose.prod.yml
# 本番向けの上書き。コマンド/再起動方針/不要ポートの抑制など。
services:
  api_gateway:
    command: >
      bash -lc "uvicorn api_gateway.app.main:app --host 0.0.0.0 --port 8000 --log-level info"
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    command: >
      bash -lc "celery -A shared.app.celery_app.celery_app worker --loglevel=info --pool=threads --concurrency=1"
    restart: unless-stopped

  scheduler:
    command: >
      bash -lc "celery -A shared.app.celery_app.celery_app beat --loglevel=info"
    restart: unless-stopped

  frontend:
    restart: unless-stopped
