# docker-compose.override.yml
# 開発用の上書き。ホットリロード・ボリュームマウント等。
services:
  api_gateway:
    build:
      target: development
    command: >
      bash -lc "uvicorn api_gateway.app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend

  worker:
    build:
      target: development
    command: >
      bash -lc "celery -A shared.app.celery_app.celery_app worker --loglevel=debug --pool=threads --concurrency=1"
    volumes:
      - ./backend:/app/backend

  scheduler:
    build:
      target: development
    command: >
      bash -lc "celery -A shared.app.celery_app.celery_app beat --loglevel=debug"
    volumes:
      - ./backend:/app/backend

  vectorstore-init:
    build:
      target: development
    volumes:
      - ./backend:/app/backend
