# docker-compose.override.yml
# version: '3.8'

services:
  frontend:
    build: { context: ./frontend }
    volumes: [./frontend/streamlit_app:/app]

  api_gateway:
    build: { context: ., target: development }
    ports: ["8000:8000"]
    volumes: ['./backend:/app/backend']
    # ホットリロード用のコマンド
    command: uvicorn backend.api_gateway.app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/backend

  worker:
    build: { context: ., target: development }
    volumes: ['./backend:/app/backend']
    # ホットリロード用のコマンド
    command: watchmedo auto-restart --directory=/app/backend --pattern=*.py --recursive -- celery -A backend.shared.app.celery_app:celery_app worker --loglevel=info --pool=threads --concurrency=1