#docker-compose.yml

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend/streamlit_app:/app
    depends_on:
      - api_gateway

  api_gateway:
    build:
      context: .
      dockerfile: ./backend/api_gateway/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    volumes:
      # api_gatewayも開発中はコードを同期させる
      - ./backend/api_gateway/app:/code/app
      - ./backend/shared:/code/shared

  worker:
    build:
      context: .
      dockerfile: ./backend/worker/Dockerfile
    deploy:
      replicas: 1 # 開発中は1台で十分
    env_file:
      - .env
    runtime: nvidia
    working_dir: /code
    environment:
      - PYTHONPATH=/code
      - NVIDIA_VISIBLE_DEVICES=all
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - OLLAMA_HOST=http://ollama:11434
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on: [ollama, rabbitmq, redis, postgres]
    volumes:
      - ./backend/worker/app:/code/app
      - ./backend/shared:/code/shared
      - ./backend/worker/data:/code/app/data
      - ./backend/scripts:/code/scripts

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./backend/worker/llm_models:/models
    deploy: { resources: { reservations: { devices: [{capabilities: [gpu]}] } } }
    runtime: nvidia

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["5672:5672", "15672:15672"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]

volumes:
  ollama_data:
  postgres_data: