# docker-compose.prod.yml
# version: '3.8'

services:
  frontend:
    build: { context: ./frontend }

  api_gateway:
    build: { context: ., target: production }
    ports: ["8000:8000"]
    command: uvicorn api_gateway.app.main:app --host 0.0.0.0 --port 8000

  worker:
    build: { context: ., target: production }
    command: celery -A shared.app.celery_app:celery_app worker --loglevel=info --pool=threads --concurrency=1
  
  ollama:
    restart: always
  
  osrm:
    restart: always

  osrm-foot:
    restart: always