# docker-compose.yml
version: '3.8'

services:
  frontend:
    ports: ["8501:8501"]
    depends_on: [api_gateway]
    profiles: ["api"] # apiプロファイルに所属

  api_gateway:
    env_file: .env
    environment: { REDIS_HOST: redis }
    depends_on: [redis, db]
    profiles: ["api"] # apiプロファイルに所属

  worker:
    deploy:
      resources:
        reservations:
          devices: [{driver: nvidia, count: all, capabilities: [gpu]}]
    runtime: nvidia
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - OLLAMA_HOST=http://ollama:11434
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} # ホスト名をdbに変更
    depends_on: [ollama, redis, db, osrm, osrm-foot, nominatim]
    profiles: ["worker"] # workerプロファイルに所属

  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes: [ollama_data:/root/.ollama]
    deploy:
      resources:
        reservations:
          devices: [{driver: nvidia, count: all, capabilities: [gpu]}]
    runtime: nvidia
    profiles: ["worker"] # workerプロファイルに所属

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    profiles: ["api", "worker"] # 両方から使われる

  db: # サービス名をpostgresからdbに変更
    image: postgres:15-alpine
    env_file: .env
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]
    profiles: ["api", "worker"] # 両方から使われる
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  osrm:
    image: osrm/osrm-backend:v5.27.1
    ports: ["5000:5000"]
    volumes: [osrm_data:/data]
    command: osrm-routed --algorithm mld /data/japan-latest.osrm
    profiles: ["worker"] # workerプロファイルに所属

  osrm-foot:
    image: osrm/osrm-backend:v5.27.1
    ports: ["5001:5000"]
    volumes: [osrm_data_foot:/data]
    command: osrm-routed --algorithm mld /data/japan-latest-foot.osrm
    profiles: ["worker"] # workerプロファイルに所属

  nominatim:
    image: mediagis/nominatim:4.4
    ports: ["8080:8080"]
    environment:
      - PBF_PATH=/data/japan-latest.osm.pbf
      - REPLICATION_URL=http://download.geofabrik.de/asia/japan-updates
    volumes:
      - ./japan-latest.osm.pbf:/data/japan-latest.osm.pbf:ro
      - nominatim_data:/var/lib/postgresql/14/main
    depends_on: [db]
    profiles: ["worker"] # workerプロファイルに所属

volumes:
  ollama_data:
  postgres_data:
  osrm_data:
  osrm_data_foot:
  nominatim_data: