# docker-compose.prod.yml (本番用)

services:
  db-init:
    build:
      target: production
  # --- API Gateway ---
  api_gateway:
    env_file: .env.gateway
    build:
      target: production
    ports:
      - "8000:8000"
    restart: always

  # --- Worker ---
  worker:
    env_file: .env.worker
    build:
      target: production
    restart: always

  db:
    ports:
      - "3306:3306"
    restart: always
  
  redis:
    ports:
      - "6379:6379"
    restart: always